apiVersion: v1
kind: api
metadata:
  plugin:
    aaa:
      namespace: add
spec:
  cluster: main
  descr: Main namespace
  ns: main
  paths: {{}}
---
apiVersion: v1
kind: api
metadata:
  plugin:
    mgmt:
      config: add
spec:
  name: default
  pull_http_timeout: {pull_http_timeout}
  push_http_timeout: {push_http_timeout}
